version: '3.9'
services:
  db:
    image: postgres:12.3-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5469:5432
    networks:
      - backend-network

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - .:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    depends_on:
      - db
    networks:
      - backend-network
    ports:
      - 8080:8080
    env_file:
      - .env

volumes:
  db-data:

networks:
  backend-network:
    driver: bridge