"""seed added for user

Revision ID: 4b9fdace471e
Revises: 5d92841ee514
Create Date: 2023-06-11 14:07:48.610049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9fdace471e'
down_revision = '5d92841ee514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('seed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'seed')
    # ### end Alembic commands ###
